### ISSUE TITLE
Delay between reports

### ISSUE THREAD

**Issue by zagub59** [koalatux/koubachi-pyserver#13]
Hi,
Koubachi-pyserver is up and running on my Raspbian Buster and I am very glad. I've managed to export csv into xml that can be read by my home automation box (eedomus). One question though, is it possible to configure the delay between reports sent by the koubachi sensor ? I've tried to change the "transmit_interval" value in get_device_config class of app.py with no luck. 

Thanks and congrats for your work !

**Comment by koalatux** [comment]
Hi,

Thanks for your request.

The `transmit_interval` is actually the value you need to change. But you have to make the Sensor aware of a config change in order for it to retrieve this new setting. Config changes are handled by comparing timestamps of the last configuration change. koubachi-pyserver uses the modification date of the file `config.yml`. I guess you just have to `touch config.yml`, restart koubachi-pyserver and then press the button on your sensor.

I also might add this as a configuration option in the future.

Cheers, Adi

**Comment by zagub59** [comment]
Hi Adi,

Thank you for your fast answer. I did just what you said and it's working great ! That's a great improvement compared to how it used to work with Koubachi legacy servers as we could not change this interval. 

Congrats again for your work and thank you from the planet to revive some dead IoT and stop wasting resources :)
