### ISSUE TITLE
sudden device problems

### ISSUE THREAD

**Issue by marksh** [koalatux/koubachi-pyserver#16]
Hi, koubachi-pyserver is running well on my Raspberry Pi 3 - but both of my Sensors lost connection today.
I tried to reach the server from other devices with `curl -sSf -o /dev/null http://myraspi:8005/ && echo "server is OK"` - all fine!
But both Sensors are showing orange blinking LED, saying "I cannot reach my server".
I am not able to connect to the Sensors as described [here](https://github.com/koubachi-sensor/api-docs#change-the-sensors-server-address) since none of my devices is willing to establish a connection to one of the Sensor. 
_Win 10pro 20H2_ and _Android 11_ are showing up the Sensor's SSID _koubachi_config (xxxxxx)_ but are not willing to connect - _macOS 11.1_ doesn't even show the Sensors.
If anyone has any ideas I would be very happy - thanks!

**Comment by marksh** [comment]
Okay, I am one step further:
Newer Windows WLAN devices [seem not to support Ad-Hoc Networks any more](https://www.intel.com/content/www/us/en/support/articles/000023257/network-and-io/wireless.html).
Connecting with macOS is still possible, when [legacy networks is enabled](https://support.apple.com/en-au/guide/mac-help/mchl98b9beb6/11.0/mac/11.0#mchl040cfb2c). 👍🏻

**Comment by marksh** [comment]
Probably a Node Red installation caused the problem. After restoring from the Pi's backup of everything works again.

Newer Windows WLAN devices [seem not to support Ad-Hoc Networks anymore](https://www.intel.com/content/www/us/en/support/articles/000023257/network-and-io/wireless.html).
Connecting with macOS is still possible, when [legacy networks is enabled](https://support.apple.com/en-au/guide/mac-help/mchl98b9beb6/11.0/mac/11.0#mchl040cfb2c).

**Comment by koalatux** [comment]
I'm glad you found the solution for your problem. And thanks for the information about the ad-hoc network, I assumed it stopped working on Windows some time ago, but I didn't have a Windows machine to verify it.
