### ISSUE TITLE
Test installation on Raspbian Buster

### ISSUE THREAD

**Issue by koalatux** [koalatux/koubachi-pyserver#2]
All dependencies are available as Debian packages in Debian buster. ~~Update the README.md with instructions on how to install these dependencies without using pip.~~

Please also test on a Raspberry Pi with Raspbian Buster.

**Comment by koalatux** [comment]
Documentation done in 1b772fd008535b19b3fe3fb9b0f480bcb7dfa35d. Tested in a fresh chroot.
Testing on Raspbian Buster still open.

**Comment by tsagadar** [comment]
Installation worked without issues on the latest Raspian from 2019-09-26 on a Raspberry Pi 4.
